# Redis 单机模式
shiro:
  redis:
    host: 127.0.0.1:6379

# Redis 集群模式
#shiro:
#  redis:
#    type: cluster
#    host: 127.0.0.1:6379,127.0.0.1:6380,127.0.0.1:6381
#    maxAttempts: 3

# Redis 哨兵模式
#shiro:
#  redis:
#    type: sentinel
#    host: 127.0.0.1:26379,127.0.0.1:26380,127.0.0.1:26381
#    masterName: mymaster